The dataset we are looking at is the measure of 10000 customers of a bank with 
- CustomerId, 
- Surname, 
- CreditScore, 
- Geography, 
- Gender, 
- Age, 
- Tenure(how long the customer has been with the bank), 
- Balance(balance of the customer at that point when the data was loaded), 
- NoOfProducts(no of produts the customer had like savings account,credit card,loan),- 
- HasCrCard(did the customer has a credit card or not), 
- IsActiveMember(is the customer an active member), 
- EstimatedSalary(estimated salary of the customer), 
- Exited(whether the person left the bank within 6 months).



In [1]:
import keras 

Using TensorFlow backend.


In [6]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
!wget https://www.dropbox.com/s/t9uil3kvmv0ypbv/Churn_Modelling.csv

'wget' is not recognized as an internal or external command,
operable program or batch file.


In [8]:
ls -l

 Volume in drive C has no label.

File Not Found



 Volume Serial Number is 9CF9-3205

 Directory of C:\Users\Basharat\_Final_Electric_load_LSTM\Workshop-ML-SP2020\6. ANN



In [9]:
dataset = pd.read_csv('data\Churn_Modelling.csv')


In [10]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [11]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [12]:
X = dataset.iloc[:, 3:13].values # pick from index 3 (CreditScore - EstimateSalary) not included Exited index13
y = dataset.iloc[:, 13].values

In [13]:
X.shape

(10000, 10)

In [14]:
X[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [15]:
y[0]

1

In [16]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [17]:
labelencoder = LabelEncoder()

In [18]:
X[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [19]:
X[:,1]  #all rows and take one column

array(['France', 'Spain', 'France', ..., 'France', 'Germany', 'France'],
      dtype=object)

In [20]:
set(X[:,1])  #looking at possible values ( France, Germany .... ) // displays Unique Values 

{'France', 'Germany', 'Spain'}

In [21]:
X[:, 1] = labelencoder.fit_transform(X[:, 1]) # taking all the values at column 1st(2nd column) , take values at 0 1 and 2 and put it back into the column 1 

In [22]:
X[0]

array([619, 0, 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [23]:
X[:,1]

array([0, 2, 0, ..., 0, 1, 0], dtype=object)

In [24]:
set(X[:,1])

{0, 1, 2}

In [25]:
X[:,2]

array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
      dtype=object)

In [26]:
set(X[:,2])

{'Female', 'Male'}

In [27]:
X[:, 2] = labelencoder.fit_transform(X[:, 2])

In [28]:
X[0]

array([619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [29]:
X[:,2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [30]:
set(X[:,2])

{0, 1}

In [67]:
#onehotencoder = OneHotEncoder(categorical_features = [1]) # for the 1 represents 1st column 
from sklearn.compose import ColumnTransformer

onehotencoder = ColumnTransformer(
    transformers=[
        ("OneHot",        # Just a name
         OneHotEncoder(), # The transformer class
         [1]              # The column(s) to be applied on.
         )
    ],
    remainder='passthrough' # donot apply anything to the remaining columns
)

In [68]:
X[0]

array([0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [71]:
#X = onehotencoder.fit_transform(X).toarray() 
X = onehotencoder.fit_transform(X) 

In [72]:
type(X)

numpy.ndarray

In [73]:
X[0]

array([1.0, 0.0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [74]:
X = X[:, 1:]

In [75]:
X[0] 

array([0.0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [76]:
from sklearn.model_selection import train_test_split

In [77]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [78]:
from sklearn.preprocessing import StandardScaler

In [79]:
sc = StandardScaler()  # standardize to mean and variance -> mean become = 0 and standard deviation = 1 

In [80]:
X_train = sc.fit_transform(X_train) # sc 

In [81]:
np.std(X_train[:,2])

0.9999999999999845

In [82]:
X_train[0]

array([-1.09168714,  1.51919821, -0.46460796,  0.00666099, -1.21571749,
        0.8095029 ,  0.64259497, -1.03227043,  1.10643166])

In [83]:
X_test = sc.transform(X_test) # uses the scaling factors used in X_train above. So only transform must be done. No Fitting

In [84]:
#Now lets make ANN

In [123]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [124]:
# Initialising the ANN
classifier = Sequential()

In [125]:
X_train.shape

(8000, 9)

In [126]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 9, kernel_initializer = 'uniform', 
                     activation = 'relu', input_dim = 9))

In [127]:
# Adding the second hidden layer
classifier.add(Dense(units = 10, kernel_initializer = 'uniform', activation = 'relu'))

In [128]:
# Adding the third hidden layer
classifier.add(Dense(units = 8, kernel_initializer = 'uniform', activation = 'relu'))

In [129]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [130]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [131]:
classifier.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_25 (Dense)             (None, 9)                 90        
_________________________________________________________________
dense_26 (Dense)             (None, 10)                100       
_________________________________________________________________
dense_27 (Dense)             (None, 8)                 88        
_________________________________________________________________
dense_28 (Dense)             (None, 1)                 9         
Total params: 287
Trainable params: 287
Non-trainable params: 0
_________________________________________________________________


In [132]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 2000, epochs = 20)


Epoch 1/20
8000/8000 [==============================] - 0s 51us/step - loss: 0.6927 - accuracy: 0.6820
Epoch 2/20
8000/8000 [==============================] - 0s 2us/step - loss: 0.6914 - accuracy: 0.7960
Epoch 3/20
8000/8000 [==============================] - 0s 2us/step - loss: 0.6901 - accuracy: 0.7960
Epoch 4/20
8000/8000 [==============================] - 0s 2us/step - loss: 0.6887 - accuracy: 0.7960
Epoch 5/20
8000/8000 [==============================] - 0s 2us/step - loss: 0.6872 - accuracy: 0.7960
Epoch 6/20
8000/8000 [==============================] - 0s 2us/step - loss: 0.6857 - accuracy: 0.7960
Epoch 7/20
8000/8000 [==============================] - 0s 3us/step - loss: 0.6840 - accuracy: 0.7960
Epoch 8/20
8000/8000 [==============================] - 0s 2us/step - loss: 0.6824 - accuracy: 0.7960
Epoch 9/20
8000/8000 [==============================] - 0s 3us/step - loss: 0.6805 - accuracy: 0.7960
Epoch 10/20
8000/8000 [==============================] - 0s 3us/step - loss: 0.67

In [133]:
#Part 3 - Making predictions and evaluating the model

In [134]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [140]:
#new_prediction = classifier.predict(sc.transform(np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_prediction = classifier.predict(sc.transform(np.array([[600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_prediction = (new_prediction > 0.5)
new_prediction

array([[False]])

In [141]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [142]:
cm

array([[1595,    0],
       [ 405,    0]], dtype=int64)